### ISSUE TITLE
Byteconf React 2020

### ISSUE THREAD

**Issue by signalnerve** [signalnerve/byteconf#1]
Byteconf React is happening on May 1st - we're currently looking for speakers!

**Comment by jgierer12** [comment]
Some speakers I'd love to see:
- @developit
- @kyleamathews
- @saravieira

**Comment by chimon2000** [comment]
Some other great speakers

- @ryanflorence
- @kentcdodds
- @diegohaz
- @jaredpalmer
- @sw-yx

**Comment by signalnerve** [comment]
As announced this morning, this is happening in October :) We're looking for speakers - are you working with React and want to tell us more in a 20-35min talk? Comment in this thread, or [send me a DM on Twitter](https://twitter.com/signalnerve)!

**Comment by signalnerve** [comment]
We've announced this conference, and the CFP is open, too! https://www.bytesized.xyz/react-2020

**Comment by soulchainer** [comment]
@signalnerve We already attended to this (I have pending watching so many of the talks, no time enough, as always xD), so... this issue could be closed already, right? ;).

**Comment by sw-yx** [comment]
woohoo!

**Comment by signalnerve** [comment]
@soulchainer indeed!!
