### ISSUE TITLE
Byteconf JavaScript 2019

### ISSUE THREAD

**Issue by signalnerve** [signalnerve/byteconf#2]
Byteconf JS is planned for March 1st and 2nd. The CFP will open later this month!

**Want to see someone speak at Byteconf JS?** Tag them here! 

Is your company interested in sponsoring Byteconf JS? Get in touch with us: conf@bytesized.xyz

<a href="https://twitter.com/byteconf/status/1035625811062255616"><img width="613" alt="screen shot 2018-11-08 at 2 44 52 pm" src="https://user-images.githubusercontent.com/922353/48229260-dedc1480-e364-11e8-8c46-1cb5fd4d6666.png"></a>

**Comment by jsjoeio** [comment]
@sdras
@kentcdodds
@KyleAMathews

**Comment by chimon2000** [comment]
Some other potential speakers

- @mikeal
- @rauchg
- @mcollina

**Comment by juanfrank7** [comment]
I'd like to nominate
@getify
@feross
@btholt

**Comment by pvinis** [comment]
I would be interested in doing a talk for rxjs.

**Comment by mikeal** [comment]
I saw that I was noted here. I just did a talk at CascadiaJS on the future of the web and how content addressing gives us a path toward creating and Internet of Data :) I could give that talk if you're interested.

**Comment by signalnerve** [comment]
Happy Byteconf ReasonML day! We're [opening the CFP for Byteconf JS](https://www.byteconf.com/js-2019) today, too 🙌

<a href="https://twitter.com/byteconf/status/1068567863978545152"><img width="614" alt="screen shot 2018-11-30 at 12 56 59 pm" src="https://user-images.githubusercontent.com/922353/49308992-71bd2a00-f49f-11e8-942e-4013b56b586d.png"></a>

Who else would you like to see speak at Byteconf JS?
