### ISSUE TITLE
Byteconf GraphQL

### ISSUE THREAD

**Issue by jsjoeio** [signalnerve/byteconf#9]
### What's the name of your proposed event? 
Byteconf GraphQL 

### What would the event cover? 

- GraphQL and what problems it solves
- case study/examples of how teams implement GraphQL
- story of a company wrapping a REST API with GraphQL
- the future of GraphQL
- The good, the bad and the ugly of GraphQL

### Do you have any speakers you'd like to see at the conference? 

@jlengstorf from Gatsby.js
@peggyrayzis from Apollo 

### Anything else you want us to know about your idea? 

Not that I can think of at this time but happy to help organize if it is chosen.

**Comment by jlengstorf** [comment]
Other smart people who could add a lot of valuable insight:

- @bdougieyo from GitHub would be a great resource here
- @rizcheldayao has rolled out GraphQL to join sprawling, incompatible enterprise systems
- @ryanomackey manages GraphQL across dozens of microservices at IBM
- @freiksenet has _deep_ knowledge of GraphQL, especially around schema stitching

**Comment by bdougie** [comment]
my expertise is talking about our 3rd party usage of our public GraphQL API, but also happy to reach out to others at GitHub if you would like a talk on how we leverage/build GraphQL internally.

**Comment by signalnerve** [comment]
Very confident this is going to happen next year 👍

**Comment by signalnerve** [comment]
Hi all! I'm back in Byteconf planning mode, and I'm starting to plan this as something we're going to do by the end of the year. More soon, will update this thread!

**Comment by signalnerve** [comment]
As announced this morning, this is happening in September :) We're looking for speakers - are you working with Svelte and want to tell us more in a 20-35min talk? Comment in this thread, or [send me a DM on Twitter](https://twitter.com/signalnerve)!

**Comment by jlengstorf** [comment]
cc @jasonbahl

**Comment by jasonbahl** [comment]
@jlengstorf i would love to! Sadly (not too sad) I can’t make it happen as I’ll be out of town on a family cruise 🛳

**Comment by horacioh** [comment]
can I apply? I've being playing with WPGraphQL and I can prepare a presentation :)

**Comment by henrikwirth** [comment]
Thanks @jasonbahl 
In general I would be happy to contribute. Depending on the time I might be able to prepare a presentation. September could be tight though.

**Comment by signalnerve** [comment]
Hi all! You may have seen that I announced Byteconf GraphQL for 1/31/2020. Our Call for Papers is now open! There's many super smart people in this thread that I'd love to have speak at the conference, check it out if you're interested!

https://www.papercall.io/byteconf-graphql-2020

@jsjoeio thanks, that's a really interesting link! I followed him, will try and send a DM his way in the next couple days 👍
